---
# Fedora CoreOS Kubernetes kubeadm join

- name: Test connection with ping
  ansible.builtin.ping:

- name: Delete /tmp/{{ inventory_hostname }} on ansible node
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    state: absent
    path: /tmp/{{ inventory_hostname }}
  when: inventory_hostname in groups.controlplane_leader

- name: Reboot all nodes
  ansible.builtin.reboot:
    post_reboot_delay: 10
    reboot_timeout: 600

- name: Test connection with ping
  ansible.builtin.ping:

- name: Wait until port 6443 is listening on control planes
  ansible.builtin.wait_for:
    port: 6443
    delay: 0
    connect_timeout: 3
    sleep: 0
  register: port_6443_check
  until: port_6443_check.failed != true
  ignore_errors: yes
  retries: 20
  when: inventory_hostname in groups.controlplanes

- name: Print port 6443 check output
  ansible.builtin.debug:
    var: port_6443_check
  when: inventory_hostname in groups.controlplanes

- name: Label worker nodes
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker
  when: inventory_hostname in groups.workers

- name: Get kubectl get no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: kubectl get no -owide
  register: kubectl_getno_output
  when: inventory_hostname in groups.controlplanes

- name: Print kubectl get no output
  ansible.builtin.debug:
    var: kubectl_getno_output.stdout_lines
  when: inventory_hostname in groups.controlplanes

- name: Get kubectl get pod
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: kubectl get pod --all-namespaces -owide
  register: get_pods
  when: inventory_hostname in groups.controlplanes

- name: Print kubectl get po output
  ansible.builtin.debug:
    var: get_pods.stdout_lines
  when: inventory_hostname in groups.controlplanes
