title: Install Kubernetes v1.25.4 on Fedora CoreOS 37 with ignition, ansible and kubeadm
description: A simple solution to install a Kubernetes test / development cluster in a fully automated way, in minutes.
theme: jekyll-theme-midnight
show_downloads: false
google_analytics:  UA-251755795-2
