---
# Fedora CoreOS remove python3-for-ansible.service

- name: remove-python3-for-ansible-service
  block:

    - name: Test connection with ping
      ansible.builtin.ping:

    - name: Disable python3-for-ansible.service
      ansible.builtin.systemd:
        name: python3-for-ansible.service
        enabled: no

    - name: Remove file /etc/python3-for-ansible.done
      ansible.builtin.file:
        path: /etc/python3-for-ansible.done
        state: absent

    - name: Remove file /etc/systemd/system/python3-for-ansible.service
      ansible.builtin.file:
        path: /etc/systemd/system/python3-for-ansible.service
        state: absent

    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Reboot
      ansible.builtin.reboot:
        post_reboot_delay: 10
        reboot_timeout: 600

    - name: Test connection with ping
      ansible.builtin.ping:

  ignore_errors: true
